### PR TITLE
fix(WEB-7276): avoid sliver of content being viewable below the `StickyFooter`

### PR DESCRIPTION
**Pull request by jkatofskyCoveo**
### Proposed Changes
Put down the sticky footer down by one pixel to avoid the visual issue reported [here](https://github.com/coveo-platform/admin-ui/pull/13077#pullrequestreview-2430781237)

### CODE REVIEW

**Comment by FelixBlaisThon** [comment]
I couldn't see the sliver in your previous PR. was it on a 4k screen ?

**Comment by jkatofskyCoveo** [comment]
@FelixBlaisThon, hmm, it's finnicky to replicate, but I don't think it has to do with 4K, rather I think it's a rounding error with how CSS calculates the bottom of a sticky element or something. Here is the modal in dev on my laptop screen (1920 X 1200). You can see the sliver
image

**Comment by jkatofskyCoveo** [comment]
Haha no you're not annoying, it's this bug that is annoying @FelixBlaisThon 😅

Windows 11, Chrome 131.

The flickering footer is indeed another issue, but for those of us who can replicate the sliver of content underneath, the flickering happens with or without the `bottom: -1px` 😕

**Comment by FelixBlaisThon** [comment]
> Haha no you're not annoying, it's this bug that is annoying @FelixBlaisThon 😅
> 
> Windows 11, Chrome 131.
> 
> The flickering footer is indeed another issue, but for those of us who can replicate the sliver of content underneath, the flickering happens with or without the `bottom: -1px` 😕

Ok. I think we have to maybe check that before merging any fix (at least remove any flickering, with or without the `bottom: -1px`.. I will create a JIRA so that we can investigate it. From the time being, I would suggest to close this PR and link the JIRA to this one https://coveord.atlassian.net/browse/ADUI-10401

**Pull request closed without merging**
