### PR TITLE
feat(website): improve guidelines look n feel

### PR DESCRIPTION
**Pull request by gdostie**
### Proposed Changes

Did some style changed recommended by the UX team to the markdown overrides so that the guidelines look better.

### Potential Breaking Changes

None

### Acceptance Criteria

-   [ ] The proposed changes are covered by unit tests
-   [ ] The potential breaking changes are clearly identified
-   [ ] [README.md](https://github.com/coveo/plasma/blob/master/README.md) is adjusted to reflect the proposed changes (if relevant)

### CODE REVIEW

**Comment by aiheon** [comment]
Missing a bit of social distancing when there's no guidelines yet  :laughing:  
image

**Comment by aiheon** [comment]
The hyperlinks are not clickable :see_no_evil: 

image

image

**Comment by gdostie** [comment]
> The hyperlinks are not clickable 🙈
> 
> image
> 
> image

Which page?

**Comment by aiheon** [comment]
> > The hyperlinks are not clickable see_no_evil
> > image
> > image
> 
> Which page?

this one is from the button page :eyes: but i've tried in others and it's the same

**Comment by gdostie** [comment]
Should be fixed now, thanks!

**Review by aiheon — APPROVED** [review]

**Review by GermainBergeron — APPROVED** [review]

**Pull request merged**
