### PR TITLE
fix(table): header alignment

### PR DESCRIPTION
**Pull request by dmgauthier**
### Proposed Changes

text-align left in the table header

**Before the Fix**
image

**After the Fix**
image

### Potential Breaking Changes

none

### Acceptance Criteria

-   [ ] The proposed changes are covered by unit tests
-   [ ] The potential breaking changes are clearly identified
-   [ ] [README.md](https://github.com/coveo/plasma/blob/master/README.md) is adjusted to reflect the proposed changes (if relevant)

### CODE REVIEW

**Comment by gdostie** [comment]
The fix looks good, but this has always bothered me about the table header style: is it expected that the background and foreground color isn't the same for headers that can be sorted and those that can't?

image
image

**Comment by GermainBergeron** [comment]
> The fix looks good, but this has always bothered me about the table header style: is it expected that the background and foreground color isn't the same for headers that can be sorted and those that can't?
> 
> image image

+1, we should remove the bold and make it the same colour (sorry @dmgauthier)

**Review by aboissinot-coveo — APPROVED** [review]
LGTM. Tested on different resolutions and it looked fine ! 👏

**Comment by dmgauthier** [comment]
I changed a bit the logic that manage the `th` width + uniformized the style between the sortable and the regular header.

**Review by GermainBergeron — APPROVED** [review]

**Pull request merged**
