### PR TITLE
feat(mantine): header redesign

### PR DESCRIPTION
**Pull request by gdostie**
### Proposed Changes

Before
image
image
image

After
image
image
image
image

### Breaking Changes

- Header breadcrumbs, actions and doc link have been moved out of the header props. You now need to use the Header sub components: `Header.Breadcrumbs`, `Header.Actions` and `Header.DocAnchor`
- Modal component override has been deleted. The exposed modal component is now the vanilla mantine modal.

Use the new `Header.Breadcrumbs` component to render breadcrumbs properly

### Acceptance Criteria

-   [x] The proposed changes are covered by unit tests
-   [x] The potential breaking changes are clearly identified
-   [x] [README.md](https://github.com/coveo/plasma/blob/master/README.md) is adjusted to reflect the proposed changes (if relevant)

### CODE REVIEW

**Comment by gdostie** [comment]
> A couple minor comments [...]

All applied!

**Comment by dmgauthier** [comment]
> Good point, same comment applies to `actions`. The current commit is a breaking change, should we take this as an opportunity to switch them all to the same pattern? However since description is usually just a string, I think it is more convenient as a prop. The actions would make sense as a children

Ok so if I understand correctly

Title : prop
Description : prop
Breadcrumb : <Header.breadCrumb /> in the children
Actions : Children ?  (are you thinking about some kind of <Header.action /> sub component ?

**Review by guscoveo — APPROVED** [review]

**Comment by gdostie** [comment]
> Ok so if I understand correctly
> 
> Title : prop
> Description : prop
> Breadcrumb : <Header.breadCrumb /> in the children
> Actions : Children ?  (are you thinking about some kind of <Header.action /> sub component ?

The title is already in children so I was think of something like

```tsx
export default () => (
    <Header
        description="The header description"
        docLink="https://about:blank"
        docLinkTooltipLabel="Tooltip text"
        borderBottom
    >
        <Header.Breadcrumbs>
            <Anchor>One</Anchor>
            <Anchor>Two</Anchor>
            <Anchor>Three</Anchor>
        </Header.Breadcrumbs>
        Title
        <Header.Actions>
            <Button>Primary</Button>
            <Button variant="outline">Secondary</Button>
        </Header.Actions>
    </Header>
);
```

**Comment by dmgauthier** [comment]
> I'm wondering if we should go all to remove the props. E.g,
> 
> ```ts
> <Header borderBottom>
>     <Header.Breadcrumbs>
>         <Anchor>One</Anchor>
>         <Anchor>Two</Anchor>
>         <Anchor>Three</Anchor>
>     </Header.Breadcrumbs>
>     Title
>     <Header.Description>The header description</Header.Description>
>     <Header.DocAnchor href="https://about:blank" label="Tooltip text" />
>     <Header.Actions>
>         <Button>Primary</Button>
>         <Button variant="outline">Secondary</Button>
>     </Header.Actions>
> </Header>
> ```
> 
> I'm not sure about the description, but for the documentation link I think it make a lot of sense

I feel the loneliness of the `title` not within a <Header.Title /> :sob:

**Pull request closed without merging**
