### PR TITLE
UI tool 209/get some result in search bar

### PR DESCRIPTION
**Pull request by aiheon**
### Proposed Changes

https://coveord.atlassian.net/browse/UITOOL-209

Now search and get results! :see_no_evil: 

### Potential Breaking Changes

Should be none

### Acceptance Criteria

-   [ ] The proposed changes are covered by unit tests
-   [X] The potential breaking changes are clearly identified
-   [ ] [README.md](https://github.com/coveo/plasma/blob/master/README.md) is adjusted to reflect the proposed changes (if relevant)

### CODE REVIEW

**Comment by FelixBlaisThon** [comment]
I don't know how it was locally, but when I type, nothing render as suggestions until I press ENTER. Also, I can't use the UP & DOWN arrows to _scroll_ through the results from the search (should it be possible?)

**Comment by aiheon** [comment]
> I don't know how it was locally, but when I type, nothing render as suggestions until I press ENTER. Also, I can't use the UP & > DOWN arrows to _scroll_ through the results from the search (should it be possible?)

The enter press is normal, we don't have query suggestions yet :see_no_evil: 

The arrows were not working locally for me also, it's something I plan to work on in another pr/jira (that with the ''no result'' behavior)

**Review by gdostie — COMMENTED** [review]
I seem to always have the 2 same homepage urls when making a search

image
image
image

**Comment by aiheon** [comment]
> I seem to always have the 2 same homepage urls when making a search
> 
> image image image

Yeah I think it's because all the components name are on the home page, I need to find a way to remove it from the result without breaking the source yet :see_no_evil:

**Comment by gdostie** [comment]
If I navigate to a component using the search bar results, the code snippet is not displayed

image

**Pull request closed without merging**
