### PR TITLE
fix(website): update `@coveo/create-atomic` to fix search-box styling issue

### PR DESCRIPTION
**Pull request by louis-bompart**
### Proposed Changes

In essence, nothing changes.
However, semantically, the website does not depend directly on `headless` anymore, but only on `@coveo/atomic-react`.
It is the onus of the UI library to care about the version of headless, not the user of the library ;) 

#### Before
image

Notice the white border on the right of the search button. ark.

#### After
image

Yeah, that's betta.

### Acceptance Criteria

-   [x] The proposed changes are covered by unit tests: N.A., dependency update, no behavioral change?
-   [x] The potential breaking changes are clearly identified: N.A.
-   [x] [README.md](https://github.com/coveo/plasma/blob/master/README.md) is adjusted to reflect the proposed changes (if relevant): N.A.

### CODE REVIEW

**Review by aiheon — APPROVED** [review]
https://giphy.com/gifs/52EZrtYlXje70ke7xC

**Comment by louis-bompart** [comment]
Mh there's a typing oopsie (was not catch on `npm start` prolly 'cause it ain't checking type by then)

Putting that in draft till I figure out, I know you fellas are quick to review and don't wanna waste your time on unbaked stuff.

**Comment by aiheon** [comment]
There's new weird behaviour now with the searchbox :thinking: 
Like if I select a suggestion and try to erase it with the delete button it just comes back xD

https://user-images.githubusercontent.com/63734941/161622185-6ab3256d-3517-43eb-b513-7557377ea7a1.mp4

**Comment by louis-bompart** [comment]
> There's new weird behaviour now with the searchbox 🤔 Like if I select a suggestion and try to erase it with the delete button it just comes back xD
> 
>  Peek.2022-04-04.15-58.mp4

:suspect: @coveo/search, that's odd, what's your take on it?

**Comment by louis-bompart** [comment]
God darn. didn't meant to close

**Review by GermainBergeron — APPROVED** [review]
Thanks for the cleanup!

**Comment by aiheon** [comment]
Not an exact science but if you select a suggestions you quickly get stuck with it in the input :woman_shrugging: 

https://user-images.githubusercontent.com/63734941/161763411-0d1bd28d-2831-4e2a-aaa7-ae66756ce8b6.mp4

**Review by mikedidomizio — APPROVED** [review]

**Comment by kdang-coveo** [comment]
I have a similar issue to @aiheon 

https://user-images.githubusercontent.com/66333175/162264065-32e4f047-205e-477f-aaa0-67717235a3ce.mp4

**Comment by louis-bompart** [comment]
Reproduced ✔️ 
@olamothe will check that out, he's the expert ;)

**Pull request closed without merging**
